runtime: python39

env_variables:
  SECRET_KEY: "your-production-secret-key"

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: auto
