services:
  - type: web
    name: stock-management
    env: python
    runtime: python-3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind :$PORT app:app
    envVars:
      - key: SECRET_KEY
        value: stock-management-render-key-2025-secure
      - key: FLASK_ENV
        value: production
      - key: GOOGLE_CREDENTIALS_BASE64
        value: [base64_encoded_credentials_here]
